#!/bin/sh
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
  exec "$AGENTOPS_REAL_PYTHON" "$@"
fi
AGENTOPS_PYTHON_WRAPPER_NAME=python
export AGENTOPS_PYTHON_WRAPPER_NAME
exec "$AGENTOPS_REAL_PYTHON" -m agentops_launcher "$@"
