apiVersion: 1
datasources:
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    uid: azure-monitor-oob
    access: proxy
    jsonData:
      cloudName: azuremonitor
      subscriptionId: ${AZURE_SUBSCRIPTION_ID}
      tenantId: ${AZURE_TENANT_ID}
      clientId: ${AZURE_CLIENT_ID}
      azureAuthType: msi
