function usage() {
  const commands = [
    'setup [--json]',
    'coverage --repo <git-repo> [--json]',
    'status',
    'latest [--file <jsonl>] [--last <duration>]',
    'live|tail [--file <jsonl>] [--last <duration>] [--follow] [--interval <seconds>]',
    'replay <session|latest> [--file <jsonl>] [--last <duration>]',
    'explain latest [--file <jsonl>] [--last <duration>]',
    'recommend latest [--file <jsonl>] [--last <duration>]',
    'open [--file <jsonl>] [--last <duration>]',
    'workflows list|show <name> [--json]',
    'plugin install|uninstall [--copilot-home <path>] [--force] [--json]',
    'agents list|path|install|uninstall [--copilot-home <path>] [--force] [--json]',
    'skills list|path|install|uninstall [--copilot-home <path>] [--force] [--json]',
    'doctor [--local-only]',
    'scan [--json]',
    'primitives [--last <duration>] [--root <path>]',
    'import-jsonl <file>',
    'custom emit --event <name> --agent <name> [--parent-agent <name>] [--delegation-id <id>] [--workflow <name>] [--step <name>] [--outcome <value>] [--risk <value>] [--score <number>] [--tag <tag>] [--custom key=value] [--attribute key=value] [--dry-run] [--json]',
    'custom import <file> [--agent <name>] [--workflow <name>] [--dry-run] [--json]',
    'annotation config-change --component <name> --target <name> [--change-type <type>] [--change-id <id>] [--version <value>] [--run-id <id>] [--session <id>] [--trace-id <id>] [--dry-run] [--json]',
    'configure show|set|import-azd [--project|--user] [--python-runtime <label>] [--node-runtime <label>] [--typescript-loader <label|unknown>] [--json]',
    'install [--shadow-copilot]',
    'otel-setup [--endpoint <url>] [--service-name <name>] [--shell bash|powershell|json]',
    'start|stop',
    'copilot [copilot-args...]',
    'codex [codex-args...]',
    'compat-check [--last <duration>]',
    'validate-collector [endpoint]',
    'validate-azure [--last <duration>] [--profile personal|team|internal] [--verify-dashboard-content] [--production] [--remediation-plan] [--json]',
    'init --local-only [--yes] [--shell bash|zsh|fish|powershell|json] [--force-skills] [--no-skills] [--json]',
    'init [--dry-run] --full [--yes] [--provision-cloud] [--import-dashboards] [--run-smoke] [--triage-latest] [--force-skills] [--no-skills] [--json]',
    'provision azure --subscription <id> --resource-group <name> [--profile pilot] [--yes] [--json]',
    'smoke [--local] [--dry-run] [--endpoint <url>] [--id <smoke-id>] [--last <duration>] [--wait <duration>] [--poll <duration>] [--open-browser] [--no-verify] [--json]',
    'attribution-smoke [--dry-run] [--endpoint <url>] [--id <smoke-id>] [--last <duration>] [--wait <duration>] [--poll <duration>] [--no-verify] [--json]',
    'live-replay-smoke [--dry-run] [--endpoint <url>] [--id <smoke-id>] [--last <duration>] [--wait <duration>] [--poll <duration>] [--no-verify] [--json]',
    'validate-enterprise [--json]',
    'ask-context <latest|session-id> [--file <jsonl>] [--last <duration>] [--json]',
    'enable-shadow',
    'disable-shadow',
    'uninstall',
    'collector start|stop',
    'saved-view add <name> --url <url> [--query-file <file>] [--description <text>] [--tag <tag>] [--events <jsonl>]',
    'saved-view list|show|open|export [name] [--events <jsonl>] [--out <dir>]',
    'link session <conversation>',
    'link trace <operationId>',
    'fields [--last <duration>]',
    'context [--last <duration>]',
    'token-rollup-audit [--last <duration>]',
    'model-tokens [--last <duration>]',
    'collector-health [--last <duration>]',
    'attribution [--last <duration>]',
    'permission-friction [--last <duration>]',
    'read-order <runId> [--session <sessionId>]',
    'slow-scripts --ledger <dir> [--top <n>]',
    'repeated-tools --ledger <dir> [--top <n>]',
    'co-activation --ledger <dir> [--top <n>]',
    'alert recommend [--last <duration>]',
    'alert tune-plan [--last <duration>] [--rule <name>] [--owner <name>]',
    'alert threshold-simulate --rule <name> --threshold <number> --owner <name> [--last <duration>]',
    'alert threshold-patch --rule <name> --threshold <number> --owner <name> [--last <duration>]',
    'alert policy [--owner <name>] [--service <name>] [--timezone <tz>]',
    'alert resources [--resource-group <name>]',
    'alert history --rule <name> [--last <duration>]',
    'alert detail --rule <name> --session <conversation> [--last <duration>]',
    'alert open --rule <name> --session <conversation> [--last <duration>]',
    'alert review --rule <name> --session <conversation> [--owner <name>] [--last <duration>]',
    'alert action-plan --rule <name> --session <conversation> [--last <duration>]',
    'alert export --rule <name> --session <conversation> --output <json> [--last <duration>]',
    'alert handoff --rule <name> --session <conversation> [--owner <name>] [--events <jsonl>] [--output <json>] [--last <duration>]',
    'alert route-plan --rule <name> --session <conversation> [--owner <name>] [--events <jsonl>] [--target <github-issue|azure-devops-work-item>] [--output <json>]',
    'alert route-github --repo <owner/repo> --rule <name> --session <conversation> --owner <github-login> [--yes]',
    'alert route-azure-devops --org <url> --project <name> --rule <name> --session <conversation> --owner <user> [--yes]',
    'alert action-group-plan --resource-group <rg> --name <name> --short-name <short> --owner <name> [--email <address>] [--webhook <url>]',
    'alert route-action-group --resource-group <rg> --scheduled-query <name> --action-group <id> --rule <name> --session <conversation> --owner <name> [--yes]',
    'incident timeline --artifact <json> [--artifact <json> ...] --output <json> [--incident <id>]',
    'lineage [--last <duration>]',
    'policy [--last <duration>]',
    'mcp [--last <duration>]',
    'benchmark list',
    'benchmark fixture-pack <fixture-dir> --id <id> [--fixture <path>] [--title <title>] [--output <file>] [--sign-key-id <id> --sign-private-key <pem>]',
    'benchmark judge-provider [--json]',
    'benchmark run <suite> --variant <name> --repeat <n> [--hypothesis <id>] [--dry-run]',
    'benchmark approve <run-id> --by <name> [--ticket <id>] [--output <json>]',
    'benchmark artifacts <run-id> [--task <task-id>] [--include-content]',
    'benchmark report <run-id> [--azure] [--last <duration>] [--approval-file <json>] [--verify-external-review]',
    'benchmark compare <before-run-id> <after-run-id> [--azure] [--last <duration>] [--approval-file <json>] [--verify-external-review]'
  ];
  return `agentops <command>\n\nCommands:\n  ${commands.join('\n  ')}\n`;
}

module.exports = {
  usage
};
